# config.yaml
image_folder_path: "/gladstone/engelhardt/lab/MarsonLabIncucyteData/AnalysisFiles/4DonorAssay/registered_images/"
# fraction of SIFT descriptors to downsample in the saved adata object
downsample_pct: 0.1
donor_ids: [1, 2, 3, 4]
# list of wells to process according to plate map (well_ids will be product of these two lists)
well_id_rows: ['B','D','F','H','J']
well_id_cols: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11']
# threshold for RFP intensity
rfp_threshold: 3.5
# list of k values to use for clustering
k_values: [3, 4, 5, 6, 7, 8, 9, 10]